sudo: false
language: ruby

rvm:
  - 2.1.0
  - 2.3.5
  - 2.4.2

before_install:
  - gem install bundler -v 1.14.6

install:
  - gem update --system
  - bundle install --jobs=3 --retry=3

cache:
  bundler: true
  directories:
    - vendor/bundle

script:
  - bin/ci
